//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VirusXStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VirusXStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirusX.VirusXStrings", typeof(VirusXStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        internal static string MainMenuExitGame {
            get {
                return ResourceManager.GetString("MainMenuExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string MainMenuHelpControls {
            get {
                return ResourceManager.GetString("MainMenuHelpControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string MainMenuHelpCredits {
            get {
                return ResourceManager.GetString("MainMenuHelpCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        internal static string MainMenuHelpGameplay {
            get {
                return ResourceManager.GetString("MainMenuHelpGameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viruses.
        /// </summary>
        internal static string MainMenuHelpViruses {
            get {
                return ResourceManager.GetString("MainMenuHelpViruses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string MainMenuNewGame {
            get {
                return ResourceManager.GetString("MainMenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string MainMenuNewGameItems {
            get {
                return ResourceManager.GetString("MainMenuNewGameItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode.
        /// </summary>
        internal static string MainMenuNewGameMode {
            get {
                return ResourceManager.GetString("MainMenuNewGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string MainMenuNewGameStart {
            get {
                return ResourceManager.GetString("MainMenuNewGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 0.9 - Campus Days + Lange Nacht Edition (2013).
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebola.
        /// </summary>
        internal static string VirusNameEbola {
            get {
                return ResourceManager.GetString("VirusNameEbola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epstein-Barr.
        /// </summary>
        internal static string VirusNameEpsteinBarr {
            get {
                return ResourceManager.GetString("VirusNameEpsteinBarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influenza.
        /// </summary>
        internal static string VirusNameH5N1 {
            get {
                return ResourceManager.GetString("VirusNameH5N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepatitis B.
        /// </summary>
        internal static string VirusNameHepatitisB {
            get {
                return ResourceManager.GetString("VirusNameHepatitisB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human immunodeficiency.
        /// </summary>
        internal static string VirusNameHIV {
            get {
                return ResourceManager.GetString("VirusNameHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marburg.
        /// </summary>
        internal static string VirusNameMarv {
            get {
                return ResourceManager.GetString("VirusNameMarv", resourceCulture);
            }
        }
    }
}
