using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VirusX
{
    /// <summary>
    /// Traditionally VirusX used resX files, so it could direclty use the autogenerated code to retrieve localized stirngs/
    /// This class ports the previous functionality.
    /// </summary>
    class VirusXStrings : DynamicObject
    {
        public static dynamic Instance { get; private set; } = new VirusXStrings();

        private static Windows.ApplicationModel.Resources.ResourceLoader loader = new Windows.ApplicationModel.Resources.ResourceLoader();

        public void SetLanguage()
        {
            // TODO.
        }

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            string loadedString = loader.GetString(binder.Name);
            if (string.IsNullOrEmpty(loadedString))
                throw new Exception(string.Format("There is no string with the identifier '{}'", binder.Name));

            result = loadedString;
            return true;
        }

        public override bool TrySetMember(SetMemberBinder binder, object value)
        {
            return false;
        }
    }
}
