//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusX {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VirusXStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VirusXStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirusX.VirusXStrings", typeof(VirusXStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Back to Main Menu ähnelt.
        /// </summary>
        internal static string BackToMainMenu {
            get {
                return ResourceManager.GetString("BackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action / Use Item ähnelt.
        /// </summary>
        internal static string ControlActionUse {
            get {
                return ResourceManager.GetString("ControlActionUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Down ähnelt.
        /// </summary>
        internal static string ControlArrowDown {
            get {
                return ResourceManager.GetString("ControlArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Left ähnelt.
        /// </summary>
        internal static string ControlArrowLeft {
            get {
                return ResourceManager.GetString("ControlArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Right ähnelt.
        /// </summary>
        internal static string ControlArrowRight {
            get {
                return ResourceManager.GetString("ControlArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Up ähnelt.
        /// </summary>
        internal static string ControlArrowUp {
            get {
                return ResourceManager.GetString("ControlArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back / Hold Cursor ähnelt.
        /// </summary>
        internal static string ControlBackHold {
            get {
                return ResourceManager.GetString("ControlBackHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamepad ähnelt.
        /// </summary>
        internal static string ControlGamepad {
            get {
                return ResourceManager.GetString("ControlGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyboard 1 ähnelt.
        /// </summary>
        internal static string ControlKeyboard1 {
            get {
                return ResourceManager.GetString("ControlKeyboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyboard 2 ähnelt.
        /// </summary>
        internal static string ControlKeyboard2 {
            get {
                return ResourceManager.GetString("ControlKeyboard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyboard 3 ähnelt.
        /// </summary>
        internal static string ControlKeyboard3 {
            get {
                return ResourceManager.GetString("ControlKeyboard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down ähnelt.
        /// </summary>
        internal static string ControlMoveDown {
            get {
                return ResourceManager.GetString("ControlMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string ControlMoveLeft {
            get {
                return ResourceManager.GetString("ControlMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string ControlMoveRight {
            get {
                return ResourceManager.GetString("ControlMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Up ähnelt.
        /// </summary>
        internal static string ControlMoveUp {
            get {
                return ResourceManager.GetString("ControlMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numpad ähnelt.
        /// </summary>
        internal static string ControlNumpad {
            get {
                return ResourceManager.GetString("ControlNumpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming, Gameplay, Graphics ähnelt.
        /// </summary>
        internal static string CreditsAndreas {
            get {
                return ResourceManager.GetString("CreditsAndreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming, Gameplay, Balancing ähnelt.
        /// </summary>
        internal static string CreditsEnrico {
            get {
                return ResourceManager.GetString("CreditsEnrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A game made by ähnelt.
        /// </summary>
        internal static string CreditsGameBy {
            get {
                return ResourceManager.GetString("CreditsGameBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2D Arts, Interface ähnelt.
        /// </summary>
        internal static string CreditsMaria {
            get {
                return ResourceManager.GetString("CreditsMaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music / Sounds ähnelt.
        /// </summary>
        internal static string CreditsMusic {
            get {
                return ResourceManager.GetString("CreditsMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming, Interface, Music / Sound ähnelt.
        /// </summary>
        internal static string CreditsSebastian {
            get {
                return ResourceManager.GetString("CreditsSebastian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special Thanks ähnelt.
        /// </summary>
        internal static string CreditsThanks {
            get {
                return ResourceManager.GetString("CreditsThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tim Benedict Jagla, Fritz and all our testers ähnelt.
        /// </summary>
        internal static string CreditsThanksNames {
            get {
                return ResourceManager.GetString("CreditsThanksNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string CurrentLanguageName {
            get {
                return ResourceManager.GetString("CurrentLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arcade ähnelt.
        /// </summary>
        internal static string GameModeArcade {
            get {
                return ResourceManager.GetString("GameModeArcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classic ähnelt.
        /// </summary>
        internal static string GameModeClassic {
            get {
                return ResourceManager.GetString("GameModeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capture the Cell ähnelt.
        /// </summary>
        internal static string GameModeCTC {
            get {
                return ResourceManager.GetString("GameModeCTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die survive as long as you can (1 player) ähnelt.
        /// </summary>
        internal static string GameModeDescriptionArcade {
            get {
                return ResourceManager.GetString("GameModeDescriptionArcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard deathmatch (2-4 players) ähnelt.
        /// </summary>
        internal static string GameModeDescriptionClassic {
            get {
                return ResourceManager.GetString("GameModeDescriptionClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die one player with a big cell against
        ///a team of three players (4 players) ähnelt.
        /// </summary>
        internal static string GameModeDescriptionCTC {
            get {
                return ResourceManager.GetString("GameModeDescriptionCTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die control a number of cells
        ///for a certain time (2-4 players) ähnelt.
        /// </summary>
        internal static string GameModeDescriptionDomination {
            get {
                return ResourceManager.GetString("GameModeDescriptionDomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die like classic mode but with
        ///some extra twists (2-4 players) ähnelt.
        /// </summary>
        internal static string GameModeDescriptionFun {
            get {
                return ResourceManager.GetString("GameModeDescriptionFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die two teams with one or two
        ///players each (2-4 players) ähnelt.
        /// </summary>
        internal static string GameModeDescriptionLvsR {
            get {
                return ResourceManager.GetString("GameModeDescriptionLvsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Domination ähnelt.
        /// </summary>
        internal static string GameModeDomination {
            get {
                return ResourceManager.GetString("GameModeDomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fun ähnelt.
        /// </summary>
        internal static string GameModeFun {
            get {
                return ResourceManager.GetString("GameModeFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left vs. Right ähnelt.
        /// </summary>
        internal static string GameModeLvsR {
            get {
                return ResourceManager.GetString("GameModeLvsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrows + ENTER ähnelt.
        /// </summary>
        internal static string InputControlNameArrows {
            get {
                return ResourceManager.GetString("InputControlNameArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Computer ähnelt.
        /// </summary>
        internal static string InputControlNameComputer {
            get {
                return ResourceManager.GetString("InputControlNameComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gampad 1 ähnelt.
        /// </summary>
        internal static string InputControlNameGamepad1 {
            get {
                return ResourceManager.GetString("InputControlNameGamepad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gampad 2 ähnelt.
        /// </summary>
        internal static string InputControlNameGamepad2 {
            get {
                return ResourceManager.GetString("InputControlNameGamepad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gampad 3 ähnelt.
        /// </summary>
        internal static string InputControlNameGamepad3 {
            get {
                return ResourceManager.GetString("InputControlNameGamepad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gampad 4 ähnelt.
        /// </summary>
        internal static string InputControlNameGamepad4 {
            get {
                return ResourceManager.GetString("InputControlNameGamepad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numpad + 0 ähnelt.
        /// </summary>
        internal static string InputControlNameNumpad {
            get {
                return ResourceManager.GetString("InputControlNameNumpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WASD + TAB ähnelt.
        /// </summary>
        internal static string InputControlNameWASD {
            get {
                return ResourceManager.GetString("InputControlNameWASD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit Game ähnelt.
        /// </summary>
        internal static string MainMenuExitGame {
            get {
                return ResourceManager.GetString("MainMenuExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controls ähnelt.
        /// </summary>
        internal static string MainMenuHelpControls {
            get {
                return ResourceManager.GetString("MainMenuHelpControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        internal static string MainMenuHelpCredits {
            get {
                return ResourceManager.GetString("MainMenuHelpCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gameplay ähnelt.
        /// </summary>
        internal static string MainMenuHelpGameplay {
            get {
                return ResourceManager.GetString("MainMenuHelpGameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viruses ähnelt.
        /// </summary>
        internal static string MainMenuHelpViruses {
            get {
                return ResourceManager.GetString("MainMenuHelpViruses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arcade Highscore ähnelt.
        /// </summary>
        internal static string MainMenuHighscore {
            get {
                return ResourceManager.GetString("MainMenuHighscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Game ähnelt.
        /// </summary>
        internal static string MainMenuNewGame {
            get {
                return ResourceManager.GetString("MainMenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items ähnelt.
        /// </summary>
        internal static string MainMenuNewGameItems {
            get {
                return ResourceManager.GetString("MainMenuNewGameItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game mode ähnelt.
        /// </summary>
        internal static string MainMenuNewGameMode {
            get {
                return ResourceManager.GetString("MainMenuNewGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string MainMenuNewGameStart {
            get {
                return ResourceManager.GetString("MainMenuNewGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Back ähnelt.
        /// </summary>
        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add computer ähnelt.
        /// </summary>
        internal static string NewGameAddComputer {
            get {
                return ResourceManager.GetString("NewGameAddComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (you need four players for this mode) ähnelt.
        /// </summary>
        internal static string NewGameCTCHelpText {
            get {
                return ResourceManager.GetString("NewGameCTCHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; press action button to join game &gt; ähnelt.
        /// </summary>
        internal static string NewGameJoinHelpText {
            get {
                return ResourceManager.GetString("NewGameJoinHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not ready ähnelt.
        /// </summary>
        internal static string NewGameNotReady {
            get {
                return ResourceManager.GetString("NewGameNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ready! ähnelt.
        /// </summary>
        internal static string NewGameReady {
            get {
                return ResourceManager.GetString("NewGameReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die remove computer ähnelt.
        /// </summary>
        internal static string NewGameRemoveComputer {
            get {
                return ResourceManager.GetString("NewGameRemoveComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show controls ähnelt.
        /// </summary>
        internal static string NewGameShowControls {
            get {
                return ResourceManager.GetString("NewGameShowControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die game starts in  ähnelt.
        /// </summary>
        internal static string NewGameStartsIn {
            get {
                return ResourceManager.GetString("NewGameStartsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◄ OFF ► ähnelt.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◄ ON ► ähnelt.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Cancel ähnelt.
        /// </summary>
        internal static string OptionsCancel {
            get {
                return ResourceManager.GetString("OptionsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fullscreen ähnelt.
        /// </summary>
        internal static string OptionsFullscreen {
            get {
                return ResourceManager.GetString("OptionsFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music ähnelt.
        /// </summary>
        internal static string OptionsMusic {
            get {
                return ResourceManager.GetString("OptionsMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screen Resolution ähnelt.
        /// </summary>
        internal static string OptionsResolution {
            get {
                return ResourceManager.GetString("OptionsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rumble ähnelt.
        /// </summary>
        internal static string OptionsRumble {
            get {
                return ResourceManager.GetString("OptionsRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Save and Exit ähnelt.
        /// </summary>
        internal static string OptionsSafeAndExit {
            get {
                return ResourceManager.GetString("OptionsSafeAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound ähnelt.
        /// </summary>
        internal static string OptionsSound {
            get {
                return ResourceManager.GetString("OptionsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die game paused ähnelt.
        /// </summary>
        internal static string PauseScreenCaption {
            get {
                return ResourceManager.GetString("PauseScreenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Continue ähnelt.
        /// </summary>
        internal static string PauseScreenContinue {
            get {
                return ResourceManager.GetString("PauseScreenContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is disconnected! ähnelt.
        /// </summary>
        internal static string PauseScreenPlayerDisconnected_disconnected {
            get {
                return ResourceManager.GetString("PauseScreenPlayerDisconnected_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player  ähnelt.
        /// </summary>
        internal static string PauseScreenPlayerDisconnected_player {
            get {
                return ResourceManager.GetString("PauseScreenPlayerDisconnected_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Quit to Menu ähnelt.
        /// </summary>
        internal static string PauseScreenQuitToMenu {
            get {
                return ResourceManager.GetString("PauseScreenQuitToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ► Play Again ähnelt.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter name... ähnelt.
        /// </summary>
        internal static string ScoreEnterYourName {
            get {
                return ResourceManager.GetString("ScoreEnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Highscore! ähnelt.
        /// </summary>
        internal static string ScoreNewHighScore {
            get {
                return ResourceManager.GetString("ScoreNewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        internal static string ScoreSubmitScore {
            get {
                return ResourceManager.GetString("ScoreSubmitScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attacker ähnelt.
        /// </summary>
        internal static string TeamNameAttacker {
            get {
                return ResourceManager.GetString("TeamNameAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defender ähnelt.
        /// </summary>
        internal static string TeamNameDefender {
            get {
                return ResourceManager.GetString("TeamNameDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team Left ähnelt.
        /// </summary>
        internal static string TeamNameLeft {
            get {
                return ResourceManager.GetString("TeamNameLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Team ähnelt.
        /// </summary>
        internal static string TeamNameNone {
            get {
                return ResourceManager.GetString("TeamNameNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team Right ähnelt.
        /// </summary>
        internal static string TeamNameRight {
            get {
                return ResourceManager.GetString("TeamNameRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.0 ähnelt.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EBOV is a select agent, World Health Organization Risk Group 4 Pathogen
        ///(requiring Biosafety Level 4-equivalent containment). ähnelt.
        /// </summary>
        internal static string VirusAdditionalInfoEbola {
            get {
                return ResourceManager.GetString("VirusAdditionalInfoEbola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is one of the most common viruses in humans. ähnelt.
        /// </summary>
        internal static string VirusAdditionalInfoEpsteinBarr {
            get {
                return ResourceManager.GetString("VirusAdditionalInfoEpsteinBarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is a highly contagious virus which is a potential pandemic threat. ähnelt.
        /// </summary>
        internal static string VirusAdditionalInfoH5N1 {
            get {
                return ResourceManager.GetString("VirusAdditionalInfoH5N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can also lead to cirrhosis and hepatocellular carcinoma. ähnelt.
        /// </summary>
        internal static string VirusAdditionalInfoHepatitisB {
            get {
                return ResourceManager.GetString("VirusAdditionalInfoHepatitisB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infection with HIV occurs by the transfer of blood, semen,
        ///vaginal fluid, pre-ejaculate, or breast milk. ähnelt.
        /// </summary>
        internal static string VirusAdditionalInfoHIV {
            get {
                return ResourceManager.GetString("VirusAdditionalInfoHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MARV is another World Health Organization Risk Group 4 Pathogen. ähnelt.
        /// </summary>
        internal static string VirusAdditionalInfoMarv {
            get {
                return ResourceManager.GetString("VirusAdditionalInfoMarv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die viral hemorrhagic fever (EBOLA fever) ähnelt.
        /// </summary>
        internal static string VirusCausedDiseaseEbola {
            get {
                return ResourceManager.GetString("VirusCausedDiseaseEbola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Implicated in several diseases that include infectious mononucleosis,
        ///multiple sclerosis and Hodgkin lymphoma. ähnelt.
        /// </summary>
        internal static string VirusCausedDiseaseEpsteinBarr {
            get {
                return ResourceManager.GetString("VirusCausedDiseaseEpsteinBarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die avian influenza (bird flu) ähnelt.
        /// </summary>
        internal static string VirusCausedDiseaseH5N1 {
            get {
                return ResourceManager.GetString("VirusCausedDiseaseH5N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hepatitis B ähnelt.
        /// </summary>
        internal static string VirusCausedDiseaseHepatitisB {
            get {
                return ResourceManager.GetString("VirusCausedDiseaseHepatitisB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die acquired immunodeficiency syndrome (AIDS) ähnelt.
        /// </summary>
        internal static string VirusCausedDiseaseHIV {
            get {
                return ResourceManager.GetString("VirusCausedDiseaseHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marburg virus disease often called Marburg hemorrhagic fever (MHF) ähnelt.
        /// </summary>
        internal static string VirusCausedDiseaseMarv {
            get {
                return ResourceManager.GetString("VirusCausedDiseaseMarv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group V; Genus Ebolavirus; Family of Filoviridae ähnelt.
        /// </summary>
        internal static string VirusClassificationEbola {
            get {
                return ResourceManager.GetString("VirusClassificationEbola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group I; Genus of Lymphocryptovirus; Family of Herpesviridae ähnelt.
        /// </summary>
        internal static string VirusClassificationEpsteinBarr {
            get {
                return ResourceManager.GetString("VirusClassificationEpsteinBarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group V; Genus A; Family of Orthomyxoviridae ähnelt.
        /// </summary>
        internal static string VirusClassificationH5N1 {
            get {
                return ResourceManager.GetString("VirusClassificationH5N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group VII; Genus Orthohepadnavirus; Family of Hepadnaviridae ähnelt.
        /// </summary>
        internal static string VirusClassificationHepatitisB {
            get {
                return ResourceManager.GetString("VirusClassificationHepatitisB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group VI; Genus Lentivirus; Family of Retroviridae ähnelt.
        /// </summary>
        internal static string VirusClassificationHIV {
            get {
                return ResourceManager.GetString("VirusClassificationHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group V; Genus Marburgvirus; Family of Filoviridae ähnelt.
        /// </summary>
        internal static string VirusClassificationMarv {
            get {
                return ResourceManager.GetString("VirusClassificationMarv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ebola ähnelt.
        /// </summary>
        internal static string VirusNameEbola {
            get {
                return ResourceManager.GetString("VirusNameEbola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Epstein-Barr ähnelt.
        /// </summary>
        internal static string VirusNameEpsteinBarr {
            get {
                return ResourceManager.GetString("VirusNameEpsteinBarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Influenza ähnelt.
        /// </summary>
        internal static string VirusNameH5N1 {
            get {
                return ResourceManager.GetString("VirusNameH5N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hepatitis B ähnelt.
        /// </summary>
        internal static string VirusNameHepatitisB {
            get {
                return ResourceManager.GetString("VirusNameHepatitisB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Human immunodeficiency ähnelt.
        /// </summary>
        internal static string VirusNameHIV {
            get {
                return ResourceManager.GetString("VirusNameHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marburg ähnelt.
        /// </summary>
        internal static string VirusNameMarv {
            get {
                return ResourceManager.GetString("VirusNameMarv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EBOV ähnelt.
        /// </summary>
        internal static string VirusShortNameEbola {
            get {
                return ResourceManager.GetString("VirusShortNameEbola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EBV ähnelt.
        /// </summary>
        internal static string VirusShortNameEpsteinBarr {
            get {
                return ResourceManager.GetString("VirusShortNameEpsteinBarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H5N1 ähnelt.
        /// </summary>
        internal static string VirusShortNameH5N1 {
            get {
                return ResourceManager.GetString("VirusShortNameH5N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HBV ähnelt.
        /// </summary>
        internal static string VirusShortNameHepatitisB {
            get {
                return ResourceManager.GetString("VirusShortNameHepatitisB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HIV ähnelt.
        /// </summary>
        internal static string VirusShortNameHIV {
            get {
                return ResourceManager.GetString("VirusShortNameHIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MARV ähnelt.
        /// </summary>
        internal static string VirusShortNameMarv {
            get {
                return ResourceManager.GetString("VirusShortNameMarv", resourceCulture);
            }
        }
    }
}
